WARNING - Неверный тип данных для объекта Runner
WARNING - Traceback (most recent call last):
  File "C:\Users\ALDAR\PycharmProjects\module_12\module_12_4.py", line 83, in test_run
    run_2 = Runner(5)
            ^^^^^^^^^
  File "C:\Users\ALDAR\PycharmProjects\module_12\module_12_4.py", line 17, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

WARNING - Неверная скорость для Runner
WARNING - Traceback (most recent call last):
  File "C:\Users\ALDAR\PycharmProjects\module_12\module_12_4.py", line 72, in test_walk
    run_1 = Runner('Ivan', -5)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALDAR\PycharmProjects\module_12\module_12_4.py", line 22, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

